stages:
  - build
  - deploy

before_script:
  - export PATH=$PATH:/usr/bin:/etc/docker

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  
image: docker:latest

build_staging:
  stage: build
  services:
    - docker:19.03.1-dind
  image: docker:19.03.1
  tags: 
    - eventpic-frontend
    - eventpic-frontend
  script:
    - docker build --pull --no-cache -t $CI_REGISTRY_IMAGE:develop .
            
deploy_develop:
  stage: deploy
  tags: 
    - eventpic-frontend
     - eventpic-frontend
  script:
    - docker rm -f hcare_frontend-dev || true
    - docker run -d -p 8080:80 --name hcare_frontend-dev --env-file ./hcare/.env --restart=always $CI_REGISTRY_IMAGE:develop
  when: manual

after_script:
  - docker ps
    
    