stages:
  - build
  - deploy
  - tags_push

##########  -  develop  -  ##########
build-image-develop:
  stage: build
  only:
    - master
  script:
    - docker build --pull --no-cache -t $CI_REGISTRY_IMAGE:develop .

deploy-develop:
  stage: deploy
  only:
    - develop
  script:
    - docker rm -f Eventpic_frontend-dev || true
    - docker run -d -p 80:80 --name Eventpic_frontend-dev --restart=always $CI_REGISTRY_IMAGE:develop
  when: manual

  # --env-file ./.env
##########  -  master  -  ##########

####################################

##########  -  tag  -  ##########
tags-push-image:
  stage: tags_push
  only:
    - tags
  except:
    - branches
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
    - docker build --pull --no-cache -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG


after_script:
  - docker ps
