version: '3.6'
services:
sample-app:
    container_name: eventpic-frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/var/www/build'
      - '/var/www/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=${NODE_ENV}